apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   labels:
     app: rancher
   name: rancher-public-name-ingress
   namespace: cattle-system
spec:
 rules:
{{- range .Values.sans }}
   - host: {{ . }}
     http:
       paths:
       - backend:
           service:
             name: rancher
             port:
               number: 80
         pathType: ImplementationSpecific
{{- end }}
 tls:
 - hosts:
{{- range .Values.sans }}
   - {{ . }}
{{- end }}
   secretName: tls-rancher-ingress
